name: Sync Repos

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Unshallow Clone (if needed)
        run: |
          if [ -f .git/shallow ]; then
            git fetch --unshallow
          else
            echo "Repository is already complete. No need to unshallow."
          fi

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB }}
        run: |
          git remote add gitlab https://Adityasinh-Sodha:$GITLAB_TOKEN@gitlab.com/Adityasinh-Sodha/MaxEdit.git
          git push gitlab main

      - name: Push to Bitbucket
        env:
          BITBUCKET_TOKEN: ${{ secrets.BITBUCKET }}
        run: |
          git remote add bitbucket https://adityasinh-sodha:$BITBUCKET_TOKEN@bitbucket.org/adityasinh-sodha/MaxEdit.git
          git push bitbucket main
