name: Sync Repos

on:
  push:
    branches:
      - main  # or the branch you want to sync

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB }}
        run: |
          git remote add gitlab https://Adityasinh-Sodha:$GITLAB_TOKEN@gitlab.com/Adityasinh-Sodha/MaxEdit.git
          git push --mirror gitlab

      - name: Push to Bitbucket
        env:
          BITBUCKET_TOKEN: ${{ secrets.BITBUCKET }}
        run: |
          git remote add bitbucket https://adityasinh-sodha:$BITBUCKET_TOKEN@bitbucket.org/Adityasinh-Sodha/MaxEdit.git
          git push --mirror bitbucket
